### ISSUE TITLE
Fails on the very first line

### ISSUE THREAD

**Issue by inspector71** [the-black-eagle/script.database.cleaner#17]
Fails on line 33: import datetime

**Comment by the-black-eagle** [comment]
Curious, datetime is a standard python library.  What version of Kodi are you using and what platform are you running it on ?

**Comment by inspector71** [comment]
LibreELEC 8.2.5 which is Kodi 17.6 I believe.

Running from SSH gets further but fails on MySQL requirement.

**Comment by the-black-eagle** [comment]
The MySQL requirement should be installed automatically when the addon is installed (script.module.myconnpy) from the Kodi repository.

If you're attempting to run it on something like an rPi, please make sure that the flashcard has some free space on it.  Connecting via SSH and then doing 'df -h' will show how much free space there is.

I mention this because I had an issue with addons not loading libraries (which were present) and it was because of a lack of free space in '/storage'.  If that isn't the case, and there is plenty of free space on the card, I'll need a Kodi debug log of you trying to start the addon.  Too big to post here so a link to it on pastebin or similar will be fine.

**Comment by the-black-eagle** [comment]
Closed as no further input from OP
