### ISSUE TITLE
Using the wrong video database and not deleting anything

### ISSUE THREAD

**Issue by jvisser** [the-black-eagle/script.database.cleaner#21]
Hi,

I am trying to get this to work. I am on Kodi 18.1. The plugin says that the video database is kodiv107 while my actual video database is kodiv116. The summary at the start indicates 248 items are to be removed. When I run nothing is removed (from either 107 or 116 database). The log file contains the correct items to be removed.

When running the addon again the summary indicates 248 items like last time.

I checked the kodi  user privileges and that does not seem the problem.

**Comment by the-black-eagle** [comment]
Yeah, the code needs updating for Leia as the highest database version it can currently connect to is 114 (which was Krypton and Leia Alpha, Beta and most RC versions).  I'll push a fix for this shortly.

I expect what is happening is that the addon is connecting to the old Krypton database (which was 107) and producing the list from that. 

Not removing redundant sources and not removing items from within the Kodi library but instead just deleting them from storage can cause issues like this, where the addon correctly identifies what needs removing but then apparently doesn't actually remove it.  This is most likely because there are some safeguards built in to stop it accidentally removing things that (may) exist.  I'm aware that the logic isn't always perfect and I do intend to re-visit it to see if it can be improved.  In the meantime, once the database version is updated, you can use the 'remove a specific path' setting to forcibly delete things.
