### ISSUE TITLE
Cleaner crashes at launch

### ISSUE THREAD

**Issue by kekukui** [the-black-eagle/script.database.cleaner#23]
> **_"A second issue regularly rears its head where the old stream paths in the videos database cause numerous problems to other functions"_**

**Would this qualify?**

`Process directory 'special://home/userdata/addon_data/plugin.video.chappaai/Movies/' does not exist - skipping scan.`

**This is what happens when launching Database Cleaner**
```
ERROR: EXCEPTION Thrown (PythonToCppException) :
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'sqlite3.OperationalError'>
Error Contents: near ")": syntax error
Traceback (most recent call last):
File "/storage/.kodi/addons/script.database.cleaner/default.py", line 685, in <module>
  cleaner_log_file(our_select, False)
File "/storage/.kodi/addons/script.database.cleaner/default.py", line 290, in cleaner_log_file
  cursor.execute(our_select)
OperationalError: near ")": syntax error
-->End of Python script error report<--
```

**Comment by the-black-eagle** [comment]
That error looks as if it's caused by a malformed SQL query.  Can you get a debug log (put both Kodi & the addon into debug) and put it on pastebin or similar and post a link here to it please.  That should show the query before it gets executed and hopefully give me an insight into what's going wrong and why.

**Comment by kekukui** [comment]
Here it is.  https://pastebin.com/a3Pnqu2n

But I had verbose logging enabled for the Database component and did not see any SQL queries being logged.  And the application log is empty, except for the version (Video Database Cleaner V0.6.0).  I can use the Python web debugger if that will help, but in any case you will need to tell me how to collect the SQL queries.

**Comment by kekukui** [comment]
https://pastebin.com/S0hzf32g

```
DEBUG: Video Database Cleaner: SQL command is DELETE FROM files WHERE idPath IN (SELECT idPath FROM path WHERE ((strPath LIKE 'rtmp://%' OR strPath LIKE 'rtmpe:%' OR strPath LIKE 'plugin:%' OR strPath LIKE 'http://%' OR strPath LIKE 'https://%') AND ()));
DEBUG: Video Database Cleaner: NO SOURCES FOUND - REMOVING rtmp(e), plugin and http info
DEBUG: Video Database Cleaner: Select Command is SELECT strPath FROM path WHERE idPath IN (SELECT idPath FROM path WHERE ((strPath LIKE 'rtmp://%' OR strPath LIKE 'rtmpe:%' OR strPath LIKE 'plugin:%' OR strPath LIKE 'http://%' OR strPath LIKE 'https://%') AND ()));
```

**Comment by the-black-eagle** [comment]
Thanks !!

Think I know what's wrong but I'll do some tests to make sure.

**Comment by the-black-eagle** [comment]
OK, I was able to reproduce your issue locally and have tested a fix that I have now implemented.  There is a new release (V0.6.1) which should no longer show that error.

**Comment by kekukui** [comment]
> **OK, I was able to reproduce your issue locally and have tested a fix that I have now implemented.** 

Great, thanks.  When I first ran this addon I was sort of tired and did not notice that you had mentioned the documentation in the preference panel.  After reading the doc file I am even more impressed with the features and the quality of the documentation.  However, I would suggest that you put a help button in the **Settings** panel, so the doc file can be displayed directly in Kodi.  The display mode used by the **Summary** function (with the smaller print) would serve this purpose well.

Since I last posted, I saw DC run to normal completion without errors -- which is puzzling to me because I dont recall playing any content since the last time I saw the error.  I guess it's not really important, just wanted to mention it.  But the video database is still almost 400,000 bytes after cleaning.  Is that normal ?

> **There is a new release (V0.6.1) which should no longer show that error.**

I decided to install your repo so I would get updates automatically.  But the installation failed.  And then I saw it has not been updated since last year anyway. 😁  So I installed the addon manually and all is good.  But just in case you might find this useful:

https://github.com/ping/instant-kodi-repo
https://gist.github.com/romanvm/fc7f4b8aa54be1957677101d0d8cad90

**Comment by the-black-eagle** [comment]
Whilst reproducing the documentation in a **Help** button in the settings certainly sounds a good idea, due to the way Kodi handles settings for addons, I don't think it would work well.  Fonts and typesize cannot be controlled (as far as I am aware) so I think the resulting large wall of text may be offputting and not reproduced in a way I would be happy with.  That said, I do agree it would be a much better place for the documentation and so I shall see if anything can be done (maybe even show the documentation on first run of the addon, with a setting to re-trigger it if required).

> Since I last posted, I saw DC run to normal completion without errors 

> 


Altering a setting could have caused this, or adding a video source.  The addon _was_ expecting a particular variable to contain something and the error ocurred if it didn't.  I should really have trapped for that originally, in the event that no settings are selected and that no local sources for video exist.

>the video database is still almost 400,000 bytes after cleaning. Is that normal ?
>
No idea !!  My own video database is 41,566,208.  Depends on how much optimisation sqlite3 does when things get deleted.  I don't know if Kodi's cleaning routine issues a vacuum command after it's done deleting stuff, but if not, there could well be empty space in there.  Might look at this for a future update.

Umm, repo...... Yeah, I always have to look up how to update the thing because the addon itself is relatively stable and doesn't need much maintenance so updates are few.  By the time I need to do it, I can't remember which version on disk it is etc etc.  Unfortunately, my co-writer on this addon decided to take a step back from things and sadly, this meant losing the repo he was hosting and updating. I'm aware this is less than ideal.

Oh, thanks for reporting the issue in the first place and the kind comments about the addon and the docs.  Makes me want to polish it even further.  Cheers !!

**Comment by kekukui** [comment]
> **I think the resulting large wall of text may be offputting and not reproduced in a way I would be happy with.**

What do you think about this?

![screenshot004](https://user-images.githubusercontent.com/20834957/60640142-adccba80-9df3-11e9-9386-a2d64c374f39.png)

https://github.com/tvaddonsco/plugin.program.indigo/blob/master/textviewer.py

In this display mode the entire text file is only 6 pages long (5 without the hard line breaks.)

**Comment by the-black-eagle** [comment]
Please see the 'docs-display' branch for an updated version that displays the documentation on first run.
